name: Typst

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: typst-community/setup-typst@v5

      - name: Compile
        run: |
          for i in *.typ; do
            typst compile "$i" "${i%typ}pdf" --ignore-system-fonts
            typst compile "$i" "${i%typ}svg" --ignore-system-fonts --pretty
            echo "[![${i%.typ}](${i%typ}svg)](${i%typ}pdf)" >> README.md
          done

      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.pdf *.svg README.md
          git commit -m build
          git push -f origin HEAD:pdf
